// Generated by gencpp from file nour_behave/ServiceExample.msg
// DO NOT EDIT!


#ifndef NOUR_BEHAVE_MESSAGE_SERVICEEXAMPLE_H
#define NOUR_BEHAVE_MESSAGE_SERVICEEXAMPLE_H

#include <ros/service_traits.h>


#include <nour_behave/ServiceExampleRequest.h>
#include <nour_behave/ServiceExampleResponse.h>


namespace nour_behave
{

struct ServiceExample
{

typedef ServiceExampleRequest Request;
typedef ServiceExampleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServiceExample
} // namespace nour_behave


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nour_behave::ServiceExample > {
  static const char* value()
  {
    return "85307ec5f3bc768c531629a831a41c88";
  }

  static const char* value(const ::nour_behave::ServiceExample&) { return value(); }
};

template<>
struct DataType< ::nour_behave::ServiceExample > {
  static const char* value()
  {
    return "nour_behave/ServiceExample";
  }

  static const char* value(const ::nour_behave::ServiceExample&) { return value(); }
};


// service_traits::MD5Sum< ::nour_behave::ServiceExampleRequest> should match
// service_traits::MD5Sum< ::nour_behave::ServiceExample >
template<>
struct MD5Sum< ::nour_behave::ServiceExampleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nour_behave::ServiceExample >::value();
  }
  static const char* value(const ::nour_behave::ServiceExampleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nour_behave::ServiceExampleRequest> should match
// service_traits::DataType< ::nour_behave::ServiceExample >
template<>
struct DataType< ::nour_behave::ServiceExampleRequest>
{
  static const char* value()
  {
    return DataType< ::nour_behave::ServiceExample >::value();
  }
  static const char* value(const ::nour_behave::ServiceExampleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nour_behave::ServiceExampleResponse> should match
// service_traits::MD5Sum< ::nour_behave::ServiceExample >
template<>
struct MD5Sum< ::nour_behave::ServiceExampleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nour_behave::ServiceExample >::value();
  }
  static const char* value(const ::nour_behave::ServiceExampleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nour_behave::ServiceExampleResponse> should match
// service_traits::DataType< ::nour_behave::ServiceExample >
template<>
struct DataType< ::nour_behave::ServiceExampleResponse>
{
  static const char* value()
  {
    return DataType< ::nour_behave::ServiceExample >::value();
  }
  static const char* value(const ::nour_behave::ServiceExampleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NOUR_BEHAVE_MESSAGE_SERVICEEXAMPLE_H
