// Generated by gencpp from file nour_behave/ServiceDetect.msg
// DO NOT EDIT!


#ifndef NOUR_BEHAVE_MESSAGE_SERVICEDETECT_H
#define NOUR_BEHAVE_MESSAGE_SERVICEDETECT_H

#include <ros/service_traits.h>


#include <nour_behave/ServiceDetectRequest.h>
#include <nour_behave/ServiceDetectResponse.h>


namespace nour_behave
{

struct ServiceDetect
{

typedef ServiceDetectRequest Request;
typedef ServiceDetectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServiceDetect
} // namespace nour_behave


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nour_behave::ServiceDetect > {
  static const char* value()
  {
    return "85307ec5f3bc768c531629a831a41c88";
  }

  static const char* value(const ::nour_behave::ServiceDetect&) { return value(); }
};

template<>
struct DataType< ::nour_behave::ServiceDetect > {
  static const char* value()
  {
    return "nour_behave/ServiceDetect";
  }

  static const char* value(const ::nour_behave::ServiceDetect&) { return value(); }
};


// service_traits::MD5Sum< ::nour_behave::ServiceDetectRequest> should match
// service_traits::MD5Sum< ::nour_behave::ServiceDetect >
template<>
struct MD5Sum< ::nour_behave::ServiceDetectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nour_behave::ServiceDetect >::value();
  }
  static const char* value(const ::nour_behave::ServiceDetectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nour_behave::ServiceDetectRequest> should match
// service_traits::DataType< ::nour_behave::ServiceDetect >
template<>
struct DataType< ::nour_behave::ServiceDetectRequest>
{
  static const char* value()
  {
    return DataType< ::nour_behave::ServiceDetect >::value();
  }
  static const char* value(const ::nour_behave::ServiceDetectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nour_behave::ServiceDetectResponse> should match
// service_traits::MD5Sum< ::nour_behave::ServiceDetect >
template<>
struct MD5Sum< ::nour_behave::ServiceDetectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nour_behave::ServiceDetect >::value();
  }
  static const char* value(const ::nour_behave::ServiceDetectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nour_behave::ServiceDetectResponse> should match
// service_traits::DataType< ::nour_behave::ServiceDetect >
template<>
struct DataType< ::nour_behave::ServiceDetectResponse>
{
  static const char* value()
  {
    return DataType< ::nour_behave::ServiceDetect >::value();
  }
  static const char* value(const ::nour_behave::ServiceDetectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NOUR_BEHAVE_MESSAGE_SERVICEDETECT_H
