// Generated by gencpp from file nour_behave/ServiceDetectResponse.msg
// DO NOT EDIT!


#ifndef NOUR_BEHAVE_MESSAGE_SERVICEDETECTRESPONSE_H
#define NOUR_BEHAVE_MESSAGE_SERVICEDETECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nour_behave
{
template <class ContainerAllocator>
struct ServiceDetectResponse_
{
  typedef ServiceDetectResponse_<ContainerAllocator> Type;

  ServiceDetectResponse_()
    : result()  {
    }
  ServiceDetectResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceDetectResponse_

typedef ::nour_behave::ServiceDetectResponse_<std::allocator<void> > ServiceDetectResponse;

typedef boost::shared_ptr< ::nour_behave::ServiceDetectResponse > ServiceDetectResponsePtr;
typedef boost::shared_ptr< ::nour_behave::ServiceDetectResponse const> ServiceDetectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nour_behave::ServiceDetectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nour_behave::ServiceDetectResponse_<ContainerAllocator1> & lhs, const ::nour_behave::ServiceDetectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nour_behave::ServiceDetectResponse_<ContainerAllocator1> & lhs, const ::nour_behave::ServiceDetectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nour_behave

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::nour_behave::ServiceDetectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nour_behave/ServiceDetectResponse";
  }

  static const char* value(const ::nour_behave::ServiceDetectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::nour_behave::ServiceDetectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceDetectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nour_behave::ServiceDetectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nour_behave::ServiceDetectResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOUR_BEHAVE_MESSAGE_SERVICEDETECTRESPONSE_H
