(cl:defpackage nour_behave-srv
  (:use )
  (:export
   "SERVICEDETECT"
   "<SERVICEDETECT-REQUEST>"
   "SERVICEDETECT-REQUEST"
   "<SERVICEDETECT-RESPONSE>"
   "SERVICEDETECT-RESPONSE"
   "SERVICEEXAMPLE"
   "<SERVICEEXAMPLE-REQUEST>"
   "SERVICEEXAMPLE-REQUEST"
   "<SERVICEEXAMPLE-RESPONSE>"
   "SERVICEEXAMPLE-RESPONSE"
  ))

